In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import datetime
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from keras.models import Sequential

# convolutional layer 만들기 위한 import
from keras.layers.convolutional import Conv2D, MaxPooling2D

# Dense layer 만들기 위한 import
from tensorflow.keras import Input, models, layers, optimizers, metrics
from tensorflow.keras.layers import Dense, Flatten, Dropout
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image

import warnings
warnings.filterwarnings("ignore")

# Can 모델 생성

In [ ]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Disable scientific notation for clarity => # 소수지수표현(과학적표기법)을 일반식으로 변경
np.set_printoptions(suppress=True)
# Load the model
model = tensorflow.keras.models.load_model('/content/drive/MyDrive/해커톤_공유폴더/t.m_model/keras_model_CAN.h5')

In [ ]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [ ]:
# 예측에 사용할 데이터(validation data)
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        PATH + 'can_mini/test',
        target_size=(224, 224),    
        # batch_size=3,
        class_mode='categorical', shuffle=False, seed=0)

# 모델 평가하기
print()
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print()
print("-- Predict --")

output = model.predict_generator(test_generator)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

print(output)

for s in range(0, len(test_generator.filenames)):
  print(test_generator.filenames[s])

Found 14 images belonging to 7 classes.

-- Evaluate --
accuracy: 78.57%

-- Predict --
[[0.953 0.004 0.033 0.002 0.006 0.000 0.002]
 [0.960 0.004 0.001 0.006 0.024 0.003 0.003]
 [0.000 0.999 0.000 0.000 0.000 0.001 0.000]
 [0.000 0.979 0.000 0.002 0.010 0.006 0.004]
 [0.493 0.012 0.300 0.181 0.005 0.003 0.006]
 [0.506 0.071 0.355 0.040 0.007 0.021 0.001]
 [0.019 0.051 0.036 0.725 0.070 0.054 0.044]
 [0.000 0.000 0.001 0.997 0.000 0.000 0.001]
 [0.000 0.012 0.000 0.000 0.987 0.001 0.000]
 [0.000 0.096 0.001 0.002 0.828 0.072 0.001]
 [0.189 0.633 0.037 0.001 0.102 0.021 0.017]
 [0.015 0.167 0.009 0.065 0.005 0.732 0.005]
 [0.000 0.008 0.000 0.001 0.000 0.000 0.991]
 [0.000 0.010 0.000 0.000 0.000 0.000 0.989]]
budweiser/budweiser_0.jpeg
budweiser/budweiser_1.jpg
coca-cola/coca_cola_0.jpg
coca-cola/coca_cola_1.jpg
edelweiser/edelweiser_0.jpg
edelweiser/edelweiser_1.png
filite/filite_0.jpg
filite/filite_1.jpg
guinness/guinness_0.jpg
guinness/guinness_1.jpg
pepsi/pepsi_0.jpg
pepsi/pepsi_1.

# PACK 모델 생성

In [ ]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Disable scientific notation for clarity => # 소수지수표현(과학적표기법)을 일반식으로 변경
np.set_printoptions(suppress=True)
# Load the model
model = tensorflow.keras.models.load_model('/content/drive/MyDrive/해커톤_공유폴더/t.m_model/keras_model_PACK.h5')

In [ ]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [ ]:
# 예측에 사용할 데이터(validation data)
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        PATH + 'pack_mini/test',
        target_size=(224, 224),    
        # batch_size=3,
        class_mode='categorical', shuffle=False, seed=0)

# 모델 평가하기
print()
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print()
print("-- Predict --")

output = model.predict_generator(test_generator)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

print(output)

for s in range(0, len(test_generator.filenames)):
  print(test_generator.filenames[s])

Found 24 images belonging to 12 classes.

-- Evaluate --
accuracy: 29.17%

-- Predict --
[[0.031 0.966 0.000 0.000 0.000 0.001 0.000 0.000 0.002 0.000 0.000 0.000]
 [0.001 0.998 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000]
 [0.000 0.007 0.001 0.000 0.001 0.000 0.000 0.000 0.062 0.000 0.007 0.921]
 [0.000 0.147 0.000 0.000 0.001 0.000 0.000 0.018 0.002 0.011 0.820 0.001]
 [0.000 0.001 0.001 0.000 0.001 0.000 0.000 0.016 0.003 0.143 0.007 0.827]
 [0.002 0.002 0.611 0.000 0.000 0.000 0.000 0.365 0.001 0.013 0.002 0.002]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.997]
 [0.000 0.006 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.001 0.000 0.992]
 [0.000 0.869 0.000 0.000 0.130 0.001 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.995 0.000 0.000 0.004 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.002 0.000 0.006 0.000 0.956 0.000 0.035 0.001 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.322 0.000 0.659 0.000 0.010 0.001 0.000 0.000 0.008]
 [0.003 0.8

# RAMYEON 모델 생성

In [ ]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Disable scientific notation for clarity => # 소수지수표현(과학적표기법)을 일반식으로 변경
np.set_printoptions(suppress=True)
# Load the model
model = tensorflow.keras.models.load_model('/content/drive/MyDrive/해커톤_공유폴더/t.m_model/keras_model_RAMYEON.h5')

In [ ]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [ ]:
# 예측에 사용할 데이터(validation data)
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        PATH + 'ramyeon_mini/test',
        target_size=(224, 224),
        class_mode='categorical', shuffle=False, seed=0)

# 모델 평가하기
print()
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print()
print("-- Predict --")

output = model.predict_generator(test_generator)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

print(output)

for s in range(0, len(test_generator.filenames)):
  print(test_generator.filenames[s])

Found 24 images belonging to 12 classes.

-- Evaluate --
accuracy: 58.33%

-- Predict --
[[0.080 0.000 0.003 0.002 0.000 0.000 0.006 0.004 0.005 0.036 0.000 0.864]
 [0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.998]
 [0.000 0.855 0.000 0.000 0.000 0.000 0.010 0.000 0.135 0.000 0.000 0.000]
 [0.000 0.826 0.000 0.000 0.000 0.000 0.000 0.000 0.173 0.000 0.000 0.000]
 [0.000 0.000 0.993 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.005]
 [0.000 0.000 0.999 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.001 0.171 0.013 0.742 0.000 0.000 0.007 0.007 0.044 0.010 0.000 0.004]
 [0.000 0.057 0.014 0.188 0.000 0.000 0.000 0.075 0.018 0.002 0.000 0.646]
 [0.002 0.017 0.012 0.006 0.003 0.000 0.006 0.000 0.755 0.153 0.000 0.047]
 [0.000 0.006 0.050 0.711 0.002 0.000 0.002 0.000 0.072 0.033 0.000 0.122]
 [0.000 0.000 0.008 0.000 0.000 0.076 0.000 0.001 0.000 0.000 0.000 0.915]
 [0.000 0.000 0.022 0.000 0.001 0.451 0.000 0.002 0.002 0.002 0.000 0.520]
 [0.000 0.0